version: "3.8"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    hostname: es.{{.Task.Slot}}
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
      - node.name=es.{{.Task.Slot}}
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es.1,es.2,es.3
      - discovery.seed_hosts=tasks.es
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.entrypoints=http"
      - "traefik.http.routers.elasticsearch.rule=Host(`${DOMAIN}`) && PathPrefix(`/es`)"
      - "traefik.http.routers.elasticsearch.middlewares=es-stripprefix"
      - "traefik.http.middlewares.es-stripprefix.stripprefix.prefixes=/es"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"
      - "traefik.http.middlewares.es-auth.basicauth.users=${USERNAME}:${HASHED_PASSWORD}"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '4'
          memory: 4G
    volumes:
      - esdata:/usr/share/elasticsearch/data
  traefik:
    image: "traefik:v2.7"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
      #- "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  esdata:
    name: '{{.Service.Name}}.{{.Task.Slot}}'